### ISSUE TITLE
http://data.nba.net/10s/prod/v2/today.json returns dead

### ISSUE THREAD

**Issue by Ant-Acid** [NBABot-Development-Team/NBABot#3]
Navigating there returns

 "Service Unavailable - DNS failure
 The server is temporarily unable to service your request. Please try again later."

I appreciate it's not your site. Just thought you should be aware.

**Comment by Ant-Acid** [comment]
And my worst fear came true. It works fine and I jumped the gun. I apologize.

**Comment by EliotChignell** [comment]
Yeah, the data.nba.net API no longer works and most of the bot has been migrated to other services, but the docs haven't yet been updated to support that.

All `cache/today.json` needs to be is 

```
{
  "seasonScheduleYear": 2022,
  "links": {
    "currentDate": "YYYYMMDD"
  }
}
```

I'll update the docs eventually

**Comment by Ant-Acid** [comment]
Appreciate you. I'm trying to convert this to work for CFB. I'll do a better job at figuring stuff out before I post issues.

**Comment by EliotChignell** [comment]
Don't worry about it at all, the code currently is in a bit of a mess but I'll see if I can polish it up to be functional in accordance with the docs.
